import { hyperscript } from './hyperscript'

export function a(props, ...childNodes) { return hyperscript('a', ...Array.from(arguments)) }
export function abbr(props, ...childNodes) { return hyperscript('abbr', ...Array.from(arguments)) }
export function address(props, ...childNodes) { return hyperscript('address', ...Array.from(arguments)) }
export function area(props, ...childNodes) { return hyperscript('area', ...Array.from(arguments)) }
export function article(props, ...childNodes) { return hyperscript('article', ...Array.from(arguments)) }
export function aside(props, ...childNodes) { return hyperscript('aside', ...Array.from(arguments)) }
export function audio(props, ...childNodes) { return hyperscript('audio', ...Array.from(arguments)) }
export function b(props, ...childNodes) { return hyperscript('b', ...Array.from(arguments)) }
export function bdi(props, ...childNodes) { return hyperscript('bdi', ...Array.from(arguments)) }
export function bdo(props, ...childNodes) { return hyperscript('bdo', ...Array.from(arguments)) }
export function blockquote(props, ...childNodes) { return hyperscript('blockquote', ...Array.from(arguments)) }
export function br(props, ...childNodes) { return hyperscript('br', ...Array.from(arguments)) }
export function button(props, ...childNodes) { return hyperscript('button', ...Array.from(arguments)) }
export function caption(props, ...childNodes) { return hyperscript('caption', ...Array.from(arguments)) }
export function cite(props, ...childNodes) { return hyperscript('cite', ...Array.from(arguments)) }
export function code(props, ...childNodes) { return hyperscript('code', ...Array.from(arguments)) }
export function col(props, ...childNodes) { return hyperscript('col', ...Array.from(arguments)) }
export function colgroup(props, ...childNodes) { return hyperscript('colgroup', ...Array.from(arguments)) }
export function data(props, ...childNodes) { return hyperscript('data', ...Array.from(arguments)) }
export function datalist(props, ...childNodes) { return hyperscript('datalist', ...Array.from(arguments)) }
export function dd(props, ...childNodes) { return hyperscript('dd', ...Array.from(arguments)) }
export function del(props, ...childNodes) { return hyperscript('del', ...Array.from(arguments)) }
export function details(props, ...childNodes) { return hyperscript('details', ...Array.from(arguments)) }
export function dfn(props, ...childNodes) { return hyperscript('dfn', ...Array.from(arguments)) }
export function dialog(props, ...childNodes) { return hyperscript('dialog', ...Array.from(arguments)) }
export function div(props, ...childNodes) { return hyperscript('div', ...Array.from(arguments)) }
export function dl(props, ...childNodes) { return hyperscript('dl', ...Array.from(arguments)) }
export function dt(props, ...childNodes) { return hyperscript('dt', ...Array.from(arguments)) }
export function em(props, ...childNodes) { return hyperscript('em', ...Array.from(arguments)) }
export function fieldset(props, ...childNodes) { return hyperscript('fieldset', ...Array.from(arguments)) }
export function figcaption(props, ...childNodes) { return hyperscript('figcaption', ...Array.from(arguments)) }
export function figure(props, ...childNodes) { return hyperscript('figure', ...Array.from(arguments)) }
export function footer(props, ...childNodes) { return hyperscript('footer', ...Array.from(arguments)) }
export function form(props, ...childNodes) { return hyperscript('form', ...Array.from(arguments)) }
export function h1(props, ...childNodes) { return hyperscript('h1', ...Array.from(arguments)) }
export function h2(props, ...childNodes) { return hyperscript('h2', ...Array.from(arguments)) }
export function h3(props, ...childNodes) { return hyperscript('h3', ...Array.from(arguments)) }
export function h4(props, ...childNodes) { return hyperscript('h4', ...Array.from(arguments)) }
export function h5(props, ...childNodes) { return hyperscript('h5', ...Array.from(arguments)) }
export function h6(props, ...childNodes) { return hyperscript('h6', ...Array.from(arguments)) }
export function header(props, ...childNodes) { return hyperscript('header', ...Array.from(arguments)) }
export function hgroup(props, ...childNodes) { return hyperscript('hgroup', ...Array.from(arguments)) }
export function hr(props, ...childNodes) { return hyperscript('hr', ...Array.from(arguments)) }
export function i(props, ...childNodes) { return hyperscript('i', ...Array.from(arguments)) }
export function img(props, ...childNodes) { return hyperscript('img', ...Array.from(arguments)) }
export function input(props, ...childNodes) { return hyperscript('input', ...Array.from(arguments)) }
export function ins(props, ...childNodes) { return hyperscript('ins', ...Array.from(arguments)) }
export function kbd(props, ...childNodes) { return hyperscript('kbd', ...Array.from(arguments)) }
export function label(props, ...childNodes) { return hyperscript('label', ...Array.from(arguments)) }
export function legend(props, ...childNodes) { return hyperscript('legend', ...Array.from(arguments)) }
export function li(props, ...childNodes) { return hyperscript('li', ...Array.from(arguments)) }
export function main(props, ...childNodes) { return hyperscript('main', ...Array.from(arguments)) }
export function mark(props, ...childNodes) { return hyperscript('mark', ...Array.from(arguments)) }
export function menu(props, ...childNodes) { return hyperscript('menu', ...Array.from(arguments)) }
export function menuitem(props, ...childNodes) { return hyperscript('menuitem', ...Array.from(arguments)) }
export function meter(props, ...childNodes) { return hyperscript('meter', ...Array.from(arguments)) }
export function nav(props, ...childNodes) { return hyperscript('nav', ...Array.from(arguments)) }
export function ol(props, ...childNodes) { return hyperscript('ol', ...Array.from(arguments)) }
export function optgroup(props, ...childNodes) { return hyperscript('optgroup', ...Array.from(arguments)) }
export function option(props, ...childNodes) { return hyperscript('option', ...Array.from(arguments)) }
export function output(props, ...childNodes) { return hyperscript('output', ...Array.from(arguments)) }
export function p(props, ...childNodes) { return hyperscript('p', ...Array.from(arguments)) }
export function pre(props, ...childNodes) { return hyperscript('pre', ...Array.from(arguments)) }
export function progress(props, ...childNodes) { return hyperscript('progress', ...Array.from(arguments)) }
export function q(props, ...childNodes) { return hyperscript('q', ...Array.from(arguments)) }
export function rb(props, ...childNodes) { return hyperscript('rb', ...Array.from(arguments)) }
export function rp(props, ...childNodes) { return hyperscript('rp', ...Array.from(arguments)) }
export function rt(props, ...childNodes) { return hyperscript('rt', ...Array.from(arguments)) }
export function rtc(props, ...childNodes) { return hyperscript('rtc', ...Array.from(arguments)) }
export function ruby(props, ...childNodes) { return hyperscript('ruby', ...Array.from(arguments)) }
export function s(props, ...childNodes) { return hyperscript('s', ...Array.from(arguments)) }
export function samp(props, ...childNodes) { return hyperscript('samp', ...Array.from(arguments)) }
export function section(props, ...childNodes) { return hyperscript('section', ...Array.from(arguments)) }
//export function select(props, ...childNodes) { return hyperscript('select', ...Array.from(arguments)) }
export function small(props, ...childNodes) { return hyperscript('small', ...Array.from(arguments)) }
export function span(props, ...childNodes) { return hyperscript('span', ...Array.from(arguments)) }
export function strong(props, ...childNodes) { return hyperscript('strong', ...Array.from(arguments)) }
export function sub(props, ...childNodes) { return hyperscript('sub', ...Array.from(arguments)) }
export function summary(props, ...childNodes) { return hyperscript('summary', ...Array.from(arguments)) }
export function sup(props, ...childNodes) { return hyperscript('sup', ...Array.from(arguments)) }
export function table(props, ...childNodes) { return hyperscript('table', ...Array.from(arguments)) }
export function tbody(props, ...childNodes) { return hyperscript('tbody', ...Array.from(arguments)) }
export function td(props, ...childNodes) { return hyperscript('td', ...Array.from(arguments)) }
//export function textarea(props, ...childNodes) { return hyperscript('textarea', ...Array.from(arguments)) }
export function tfoot(props, ...childNodes) { return hyperscript('tfoot', ...Array.from(arguments)) }
export function th(props, ...childNodes) { return hyperscript('th', ...Array.from(arguments)) }
export function thead(props, ...childNodes) { return hyperscript('thead', ...Array.from(arguments)) }
export function time(props, ...childNodes) { return hyperscript('time', ...Array.from(arguments)) }
export function tr(props, ...childNodes) { return hyperscript('tr', ...Array.from(arguments)) }
export function track(props, ...childNodes) { return hyperscript('track', ...Array.from(arguments)) }
export function tt(props, ...childNodes) { return hyperscript('tt', ...Array.from(arguments)) }
export function u(props, ...childNodes) { return hyperscript('u', ...Array.from(arguments)) }
export function ul(props, ...childNodes) { return hyperscript('ul', ...Array.from(arguments)) }
export function video(props, ...childNodes) { return hyperscript('video', ...Array.from(arguments)) }
export function wbr(props, ...childNodes) { return hyperscript('wbr', ...Array.from(arguments)) }